vich_uploader:
    db_driver: orm
    mappings:
        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
        users:
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
